[[doing]]
title = "Growth"
icon = "./config/assets/icons/mobile.svg"
text = "Conceptualizing ideas and exploring avenues towards 0 to 1."

[[doing]]
title = "Automation"
icon = "./config/assets/icons/code.svg"
text = "Researching and implementing web and mobile automation."

[[doing]]
title = "Content"
icon = "./config/assets/icons/compass.svg"
text = "Design and content creation to boost your brand experience."

[[doing]]
title = "Startup"
icon = "./config/assets/icons/laptop-code.svg"
text = "Building my own accessible community-sharing micro-SaaS."
