[[project]]
title = "2D Animation"
category = "Video Editing"
image = "https://i.imgur.com/7x5ZaSR.jpg"
url = "https://www.youtube.com/watch?v=N6foRJhimMU&t=1s"

[[project]]
title = "Brand Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/9iqycUO.jpg"
url = "https://www.youtube.com/watch?v=BaloSk-VTFE"

[[project]]
title = "Himalayas Travel Video"
category = "Video Editing"
image = "https://i.imgur.com/CVmoQDm.png?"
url = "https://drive.google.com/file/d/17mMLqjwjIP6-4lwrRSbMtvP1E16OfesU/view"

[[project]]
title = "Ad Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/uHC1aPK.jpg"
url = "https://www.youtube.com/watch?v=-O5T3utR7Qw"

[[project]]
title = "New Collection Release"
category = "Landing Page Design"
image = "https://d213t4exkgxsjh.cloudfront.net/assets/images/sdj-banner.jpg"
url = "https://www.michaeltrio.com/jewellery/si-dian-jin"

[[project]]
title = "Store Launch Press Release"
category = "Edtiorial Content"
image = "https://scontent.fsin15-1.fna.fbcdn.net/v/t1.6435-9/60015583_2186368204774434_4080552439705501696_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=83ddde&_nc_ohc=r2VaIgj4okQAX9WnP5I&_nc_ht=scontent.fsin15-1.fna&oh=00_AfAHh6LUXFFZ343A5sqP73Ym2PHWCfOvx44xVDRM-w-15g&oe=65B88EB1"
url = "https://web.archive.org/web/20200927091756/https://www.michaeltrio.com/blog/this-homegrown-custom-jewellery-brand-is-opening-its-second-store-in-the-heartlands/"

[[project]]
title = "Orizon"
category = "Web development"
image = "./config/assets/projects/project-2.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Fundo"
category = "Web design"
image = "./config/assets/projects/project-3.jpg"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

[[project]]
title = "Brawlhalla"
category = "Applications"
image = "./config/assets/projects/project-4.png"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "DSM."
category = "Web design"
image = "./config/assets/projects/project-5.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "MetaSpark"
category = "Web design"
image = "./config/assets/projects/project-6.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Summary"
category = "Web development"
image = "./config/assets/projects/project-7.png"
url = "https://github.com/ivansaul/codigo_facilito_downloader"

[[project]]
title = "Task Manager"
category = "Applications"
image = "./config/assets/projects/project-8.jpg"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "Arrival"
category = "Web development"
image = "./config/assets/projects/project-9.png"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"
