[[project]]
title = "2D Animation"
category = "Video Editing"
image = "https://i.imgur.com/7x5ZaSR.jpg"
url = "https://www.youtube.com/watch?v=N6foRJhimMU&t=1s"

[[project]]
title = "Brand Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/9iqycUO.jpg"
url = "https://www.youtube.com/watch?v=BaloSk-VTFE"

[[project]]
title = "Himalayas Travel Video"
category = "Video Editing"
image = "https://i.imgur.com/CVmoQDm.png?"
url = "https://drive.google.com/file/d/17mMLqjwjIP6-4lwrRSbMtvP1E16OfesU/view"

[[project]]
title = "Ad Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/uHC1aPK.jpg"
url = "https://www.youtube.com/watch?v=-O5T3utR7Qw"

[[project]]
title = "New Collection Release"
category = "Landing Page Design"
image = "https://d213t4exkgxsjh.cloudfront.net/assets/images/sdj-banner.jpg"
url = "https://www.michaeltrio.com/jewellery/si-dian-jin"

[[project]]
title = "Store Launch Press Release"
category = "Edtiorial Content"
image = "https://scontent.fsin15-1.fna.fbcdn.net/v/t1.6435-9/60015583_2186368204774434_4080552439705501696_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=83ddde&_nc_ohc=r2VaIgj4okQAX9WnP5I&_nc_ht=scontent.fsin15-1.fna&oh=00_AfAHh6LUXFFZ343A5sqP73Ym2PHWCfOvx44xVDRM-w-15g&oe=65B88EB1"
url = "https://web.archive.org/web/20200927091756/https://www.michaeltrio.com/blog/this-homegrown-custom-jewellery-brand-is-opening-its-second-store-in-the-heartlands/"

[[project]]
title = "Brand Video"
category = "Storyboarding"
image = "https://i.imgur.com/AnDyl6r.jpg"
url = "https://www.youtube.com/watch?v=2Wru9DZkbPA"

[[project]]
title = "Love & Differences"
category = "Storyboarding"
image = "https://i.imgur.com/9Y4yLd0.jpg"
url = "https://www.youtube.com/watch?v=Iyxdd8kUhJU"

[[project]]
title = "Tiktok 300K Views"
category = "Storyboarding"
image = "https://i.imgur.com/fNAM5hA.jpg"
url = "https://www.tiktok.com/@yycircle/video/6910127833696275714"

[[project]]
title = "KooBits Media Post"
category = "Digital Marketing"
image = "https://scontent.fsin15-2.fna.fbcdn.net/v/t39.30808-6/216948668_4159803487436497_8657213716922078319_n.png?_nc_cat=104&ccb=1-7&_nc_sid=3635dc&_nc_ohc=WZcG79daeMgAX9sJGpg&_nc_ht=scontent.fsin15-2.fna&oh=00_AfAB0bENvqTMz57Nz5vJsB_NY7m-2Pqg5ubwSs-QOTc6fA&oe=6596C580g"
url = "https://www.facebook.com/KooBits/photos/pb.100064322186659.-2207520000/4159803480769831/?type=3"

[[project]]
title = "KooBits Ad Post"
category = "Digital Marketing"
image = "https://i.imgur.com/FpsQQVi.jpg"
url = "https://www.facebook.com/ads/library/?active_status=all&ad_type=political_and_issue_ads&country=SG&id=361707445227805&media_type=all"

[[project]]
title = "Retargeting Ad Campaign"
category = "Landing Page Design"
image = "https://i.imgur.com/VGmEPNG.jpg"
url = "https://www.koobits.com/math?k21t=facebook&utm_source=facebook&utm_medium=cpc&utm_campaign=ftretargeting&utm_content=testgirl"

[[project]]
title = "YY Food Series"
category = "Storyboarding"
image = "https://i.imgur.com/KYfbLfM.jpg"
url = "https://www.youtube.com/watch?v=ufB9wZLRvgQ"
