[[project]]
title = "2D Animation"
category = "Video Editing"
image = "https://i.imgur.com/7x5ZaSR.jpg"
url = "https://www.youtube.com/watch?v=N6foRJhimMU&t=1s"

[[project]]
title = "Brand Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/9iqycUO.jpg"
url = "https://www.youtube.com/watch?v=BaloSk-VTFE"

[[project]]
title = "Himalayas Travel Video"
category = "Video Editing"
image = "https://i.imgur.com/CVmoQDm.png?"
url = "https://drive.google.com/file/d/17mMLqjwjIP6-4lwrRSbMtvP1E16OfesU/view"

[[project]]
title = "Ad Campaign"
category = "Storyboarding"
image = "https://i.imgur.com/uHC1aPK.jpg"
url = "https://www.youtube.com/watch?v=-O5T3utR7Qw"

[[project]]
title = "New Collection Release"
category = "Landing Page Design"
image = "https://i.imgur.com/aWcrq2U.jpg"
url = "https://www.michaeltrio.com/jewellery/si-dian-jin"

[[project]]
title = "Store Launch Press Release"
category = "Edtiorial Content"
image = "https://www.michaeltrio.com/blog/wp-content/uploads/2023/05/jem-shop2-1024x768.jpg"
url = "https://www.michaeltrio.com/blog/this-homegrown-custom-jewellery-brand-is-opening-its-second-store-in-the-heartlands/"

[[project]]
title = "Brand Video"
category = "Storyboarding"
image = "https://i.imgur.com/AnDyl6r.jpg"
url = "https://www.youtube.com/watch?v=2Wru9DZkbPA"

[[project]]
title = "Love & Differences"
category = "Storyboarding"
image = "https://i.imgur.com/9Y4yLd0.jpg"
url = "https://www.youtube.com/watch?v=Iyxdd8kUhJU"

[[project]]
title = "Tiktok 300K Views"
category = "Storyboarding"
image = "https://i.imgur.com/fNAM5hA.jpg"
url = "https://www.tiktok.com/@yycircle/video/6910127833696275714"

[[project]]
title = "KooBits Media Post"
category = "Digital Marketing"
image = "https://i.imgur.com/D7ZUW1o.png"
url = "https://www.facebook.com/KooBits/photos/pb.100064322186659.-2207520000/4159803480769831/?type=3"

[[project]]
title = "KooBits Ad Post"
category = "Digital Marketing"
image = "https://i.imgur.com/FpsQQVi.jpg"
url = "https://www.facebook.com/ads/library/?active_status=all&ad_type=political_and_issue_ads&country=SG&id=361707445227805&media_type=all"

[[project]]
title = "Retargeting Ad Campaign"
category = "Landing Page Design"
image = "https://i.imgur.com/VGmEPNG.jpg"
url = "https://www.koobits.com/math?k21t=facebook&utm_source=facebook&utm_medium=cpc&utm_campaign=ftretargeting&utm_content=testgirl"

[[project]]
title = "YY Food Series"
category = "Storyboarding"
image = "https://i.imgur.com/KYfbLfM.jpg"
url = "https://www.youtube.com/watch?v=ufB9wZLRvgQ"
