############## Education config #################
#################################################
[[education]]
title = "Republic Polytechnic, Dip. Mass Comm"
timeline = "2009 — 2012"
description = "This was where Advertising, Branding, Copywriting and Design grew on Hansel. Hansel clinched first place for NYDC Restaurant's Advertising & Copywriting competition."

[[education]]
title = "SIM-RMIT, BA. Prof Comms"
timeline = "2014 — 2015"
description = "Due to module exemption, Hansel obtained the degree in a year. During this period, Hansel handled multiple advertising & PR projects for local companies."


############## Experience config ################
#################################################
[[experience]]
title = "Content Marketing Executive"
timeline = "2017 — 2019"
description = "In 2 years, I boosted Michael Trio’s social presence, curated promo videos, hosted collaborations and events, and even assisted in the rebranding of the company. I churned SEO-friendly articles and handled all new product collections & descriptions, company write-ups & press releases. I also oversee the SEO/SEM budget, ensuring all content met our brand guidelines."

[[experience]]
title = "Copywriter, Content Writer"
timeline = "2020 — 2020"
description = "As a copywriter, I helped revamp the content for YYCircle's websites and lifestyle mobile application, while creating content for their social media and crafting SEO-optimized articles as well. Being a part of the start-up culture, I contributed heavily with other content production like videos, scripting and storyboarding, and did a bit of 2D animation content with Premiere Pro."

[[experience]]
title = "Marketing Content Copywriter & Designer"
timeline = "2020 — 2022"
description = "At KooBits, a fast-growing EdTech start-up, I handled the creation of landing pages and visuals to boost user acquisition. From simple html and CSS, to designing images for META and Google ads, I got to fulfil my passion for content creation. About 3 months in, I got the chance to take up the role of Digital Ads Manager, and explored the world of performance marketing."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Marketing & Copywriting"
value = "80%"

[[skill]]
title = "Branding & Design"
value = "70%"

[[skill]]
title = "Content Creation & Strategy"
value = "90%"

[[skill]]
title = "HTML/CSS"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "90%"

[[language]]
title = "Mandarin"
value = "70%"
