############## Education config #################
#################################################
[[education]]
title = "Republic Polytechnic, Dip. Mass Comm"
timeline = "2009 — 2012"
description = "Duis aute irure dolor in reprehenderit in voluptate, quila voluptas mag odit aut fugit, sed consequuntur magni dolores eos."

[[education]]
title = "SIM-RMIT, BA. Prof Comms"
timeline = "2014 — 2015"
description = "Due to module exemption, Hansel obtained the degree upgrade in a year. During this period, the final prototype handled multiple advertising & PR projects for local companies."


############## Experience config ################
#################################################
[[experience]]
title = "Web designer"
timeline = "2010 — 2013"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Art director"
timeline = "2013 — 2015"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Creative director"
timeline = "2015 — Present"
description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Web design"
value = "80%"

[[skill]]
title = "Graphic design"
value = "70%"

[[skill]]
title = "Branding"
value = "90%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Ingles"
value = "60%"

[[language]]
title = "French"
value = "50%"
