############### Section config ##################
#################################################
title = "Competence"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "High Adaptability"
icon = "./config/assets/icons/bolt.svg"
text = "I have the ability to quickly acquire new knowledge and adapt to changing environments."

[[skills]]
title = "Intuitive"
icon = "./config/assets/icons/comment.svg"
text = "Hansel is a combination of quick-wit, target audience comprehension and a driven initiative."

[[skills]]
title = "Team Player"
icon = "./config/assets/icons/user.svg"
text = "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."

[[skills]]
title = "Innovative"
icon = "./config/assets/icons/gear.svg"
text = "With Hansel, being creative isn’t enough - creating fresh content and unique experiences to invoke emotions is the new currency."
