############### Section config ##################
#################################################
title = "Proficiencies"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
typescript = "./config/assets/icons/typescript.svg"
facebook = "./config/assets/icons/facebook.svg"
n8n = "./config/assets/icons/n8n-color.svg"
figma = "./config/assets/icons/figma.svg"
instagram = "./config/assets/icons/instagram.svg"
sanity = "./config/assets/icons/sanity.svg"
photoshop = "./config/assets/icons/photoshop.svg"
illustrator = "./config/assets/icons/illustrator.svg"
premiere = "./config/assets/icons/premiere.svg"
aftereffects = "./config/assets/icons/aftereffects.svg"
wordpress = "./config/assets/icons/wordpress.svg"
